name: Build

on:
  push:
    branches:
      - main

env:
  JAVA_DISTRIBUTION: corretto
  JAVA_VERSION: 17
  VERSION_CODE: ${{ github.run_number }}
  VERSION_NAME: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SunChulBaek/build_android@v1
        with:
          java-distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          base64-keystore: ${{ secrets.BASE64_KEYSTORE }}
          release-key-alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          release-key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}
          release-store-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
          version-code: ${{ env.VERSION_CODE }}
          version-name: ${{ env.VERSION_NAME }}
          artifact-name: "${{ vars.APK_NAME }}-${{ env.VERSION_CODE }}"
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}